# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
volumes:
  postgres: